name: Publish Docker image

on: push

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - uses: actions/checkout@master
        with:
          name: odoo/docker     <-- clone https://github.com/odoo/docker.git
          ref: refs/heads/release
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: raviteja1996/ravi
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v1
        with:
          context: .
          push: true
