name: Publish Docker image

on: push

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      
        
      - uses: actions/checkout@master
        with:
          name: odoo/docker     <-- clone https://github.com/odoo/docker.git
          
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
      
      
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v1
        with:
          command: cd odoo/docker/16.0
          context: .
          push: true
