name: Publish Docker image

on: push

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      
        
      
          
      
      - name: Checkout public odoo 
        uses: actions/checkout@v2
        with:
          repository: odoo/docker
          
          path: docker
      
      
      
      - name: Build, tag, and push image to Docker Hub
        id: build-image
        env:
          IMAGE_TAG: latest
        run: |
          cd odoo/docker/16.0
          docker build -t odoo-new .
          
          docker odoo-new
          
